AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket created using CloudFormation

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "my-uniques-bucket-${AWS::AccountId}-${AWS::Region}"
