name: Deploy S3 via CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy S3 Bucket
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file s3-bucket.yaml \
            --stack-name my-s3-bucket-stack \
            --capabilities CAPABILITY_NAMED_IAM
