name: Full SAM-Based CloudFormation Pipeline

on:
  push:
    branches:
      - master

env:
  ASSET_BUCKET_NAME: cf-asset-bucket-us-east-1-sandbox

jobs:
  deploy:
    name: Deploy Root Stack
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Deploy root stack
        run: |
          aws cloudformation deploy \
            --template-file root.yaml \
            --stack-name root-nested-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides AssetBucket=${{ env.ASSET_BUCKET_NAME }}
