name: Full SAM-Based CloudFormation Pipeline

on:
  push:
    branches:
      - master

env:
  ASSET_BUCKET_NAME: cf-asset-bucket-us-east-1-sandbox

jobs:
  init-bucket:
    name: Create Artifact S3 Bucket
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Deploy asset bucket
        run: |
          aws cloudformation deploy \
            --template-file s3-asset-bucket.yaml \
            --stack-name cf-asset-bucket-stack \
            --parameter-overrides AssetBucketName=${{ env.ASSET_BUCKET_NAME }}

  build:
    name: Lint & Upload to S3
    needs: init-bucket
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Lint CloudFormation Templates
        run: |
          cfn-lint root.yaml
          cfn-lint s3.yaml
          cfn-lint lambda/lambda.yaml

      - name: Upload all project files to S3
        run: |
          aws s3 cp . s3://${{ env.ASSET_BUCKET_NAME }}/ --recursive \
          --exclude "*" \
          --include "root.yaml" \
          --include "s3.yaml" \
          --include "lambda/*"

  deploy:
    name: Deploy Root Stack
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy root stack
        run: |
          aws cloudformation deploy \
            --template-file root.yaml \
            --stack-name root-nested-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides AssetBucket=${{ env.ASSET_BUCKET_NAME }}
